spring:
    datasource:
        url: jdbc:mysql://localhost:3306/javafullstack
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
# create , create-drop,validate,update


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: /my-actuator

  endpoint:
    shutdown:
      enabled: true
       
       
server:
  servlet:
    context-path: /blog-app

springdoc:
  swagger-ui:
    path: /mypath