spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javafullstack
    username: root
    password: root
  jpa:
   hibernate:
    #ddl-auto: create
    ddl-auto: update
  application:
    name: coupen-service
    
  zipkin:
    base-url: http://127.0.0.1:9411/
  
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active:
    - dev
    
    
#server:
#  port: 8082    

  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    